### ISSUE TITLE
Need a way to tell worker to "shut down once all scheduled work is complete"

### ISSUE THREAD

**Issue by dkornishev** [Dreckr/Worker#10]
Once I've scheduled all the tasks, I'd like to be able to tell worker to close after it is done executing.

**Comment by Dreckr** [comment]
There's some work to be done on how to handle scheduled tasks when 'close' is called. Currently, if a worker is closed with pending tasks, their futures hang forever. I think I'll add an optional flag to 'close' called 'whenDone'.

**Comment by Dreckr** [comment]
Fixed!
