### ISSUE TITLE
High stack_trace expectations

### ISSUE THREAD

**Issue by Goutte** [Dreckr/Worker#12]
Pub 1.4.3 itself depends on max `barback 0.13.0-dev`.

```
Incompatible version constraints on stack_trace:
- barback 0.13.0 depends on version >=0.9.1 <0.10.0
- worker 0.3.10 depends on version >=1.0.0 <2.0.0
```

Does worker really requires `stack_trace` 1.0.0 ? Can we safely loosen the min version boundary to `0.9.1` ?

**Comment by Dreckr** [comment]
Fixed on 0.3.11. Thanks for reporting!
