### ISSUE TITLE
Starting more tasks then processors exist results in a exception 

### ISSUE THREAD

**Issue by nkratzke** [Dreckr/Worker#5]
Starting more tasks then processors exists results in a exception.
The following code

```
import "package:worker/worker.dart";
import "dart:async";

class FibTask extends Task {
  final _v;
  FibTask(this._v);
  execute() => fib(_v);
}

num fib(n) {
  if (n == 0) return 0;
  if (n == 1) return 1;
  return fib(n-1) + fib(n-2);
}

void main() {
  final isolates = new Worker();
  var parallels = [];
  for (var i in [10, 20, 30, 40, 30, 20]) {
    parallels.add(isolates.handle(new FibTask(i)));
  }

  Future.wait(parallels).then((r) {
    print(r);
  });
}
```

results on a four processor system into the following exception (in _WorkerIsolateImpl getter scheduledTask).

```
Breaking on exception: type 'EfficientLengthMappedIterable<_ScheduledTask, dynamic>' is not a subtype of type 'List<Task>' of 'function result'.
```

Everything works fine if less tasks then processors exist are started. So

```
  final isolates = new Worker();
  var parallels = [];
  for (var i in [10, 20, 30]) {
    parallels.add(isolates.handle(new FibTask(i)));
  }

  Future.wait(parallels).then((r) {
    print(r);
  });
```

works fine on a four processor system.

**Comment by Dreckr** [comment]
Fixed on 08e5ad78892747854e5f6cbeb9f0ca0049c8df76

Remember to close your Worker instance on Future.wait handler:

``` dart
Future.wait(parallels).then((r) {
    print(r);
    isolates.close();
  });
```

Thanks for reporting! You are awesome!

Edit: I'll release a version ASAP.

**Comment by Dreckr** [comment]
@nkratzke, may I add your code to the other examples?

**Comment by nkratzke** [comment]
Of course.
Nane
Am 15.02.2014 23:46 schrieb "Diego Rocha" notifications@github.com:
