### ISSUE TITLE
WorkerIsolate from Pub doesn't have factory constructor

### ISSUE THREAD

**Issue by akserg** [Dreckr/Worker#6]
Version of Worker on Pub and in repository are different. 
I can't instantiate WorkerIsolate when I use pub version of Worker. I find other differences. Please publish current worker version on Pub.

**Comment by Dreckr** [comment]
I wished to make more changes for the next version, but I don't see it happening anytime soon. I'll push a minor update with the fixes asap.

Thanks for reporting!

**Comment by akserg** [comment]
Big thanks.
