### ISSUE TITLE
Task.execute MUST return a value or the returned future never completes

### ISSUE THREAD

**Issue by dkornishev** [Dreckr/Worker#8]
Adding explicit return statement without a value does not remedy the situation.
Only returning something (anything) causes the future to complete.

Few examples below:

``` dart
void execute() {
    print("Executing");
}
```

``` dart
void execute() {
    return new Future(() {
       print("Executing");  
    });
}
```

**Comment by Dreckr** [comment]
Thanks for reporting! Fixed on bea10a951f32ebcb29911b3568cf956a29323aa9.

Any other small fix that I can do for the next release?

**Comment by dkornishev** [comment]
I am currently trying to splice worker into dherkin, so I report issues as I find them.

Great work on the library, btw.  Probably easiest concurrency ever :)

**Comment by Dreckr** [comment]
Awesome and thanks!

I'll release 0.3.10 and if have any suggestions about the API or documentation, you can email me anytime. It's great to get some feedback.
